name: bump-homebrew-formula
description: "Bump Homebrew formula after a new release"
author: "@mislav"
runs:
  using: node12
  main: "./lib/index.js"
inputs:
  formula-name:
    description: The name of the Homebrew formula
    required: true
  homebrew-tap:
    description: The repository where the formula should be updated
    default: s-anjana/homebrew-core
  base-branch:
    description: The branch name in the homebrew-tap repository where the formula should be updated
  commit-message:
    description: The git commit message template to use when updating the formula
    default: |
      {{formulaName}} {{version}}

      Updated by https://github.com/s-anjana/bump-homebrew-formula-action
branding:
  icon: circle
  color: orange
